// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923214713_AddPushDeviceContentLocale")]
    partial class AddPushDeviceContentLocale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.CatalogFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BaselineEstablishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NotifyFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NotifyMovieRelease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotifyNewEpisodes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotifyNewSeasons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ContentType", "ContentId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "ContentType", "ContentId")
                        .IsUnique();

                    b.ToTable("catalog_follows", null, t =>
                        {
                            t.HasCheckConstraint("CK_catalog_follows_content_type", "\"ContentType\" IN ('Movie', 'Tv')");
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.CatalogReleaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReleaseAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.HasIndex("MovieId");

                    b.HasIndex("ReleaseAtUtc");

                    b.HasIndex("TvShowId");

                    b.ToTable("catalog_release_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_catalog_release_events_content_ref", "(\"TvShowId\" IS NOT NULL AND \"MovieId\" IS NULL) OR (\"TvShowId\" IS NULL AND \"MovieId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en-US");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedDeliverySecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("StillPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VoteAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AirDate");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasFilter("\"ImdbId\" IS NOT NULL");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasFilter("\"TvdbId\" IS NOT NULL");

                    b.HasIndex("SeasonId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TvShowId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasFilter("\"MovieId\" IS NOT NULL");

                    b.HasIndex("UserId", "TvShowId")
                        .IsUnique()
                        .HasFilter("\"TvShowId\" IS NOT NULL");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TmdbKeywordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TmdbKeywordId")
                        .IsUnique();

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CollectionBackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CollectionPosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("KeywordsSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TmdbCollectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VoteAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasFilter("\"ImdbId\" IS NOT NULL");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("Title");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasFilter("\"TvdbId\" IS NOT NULL");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieKeyword", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.HasKey("MovieId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("movie_keywords", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MoviePerson", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreditType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Job")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Character")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MovieId", "PersonId", "CreditType", "Job");

                    b.HasIndex("PersonId");

                    b.ToTable("movie_people", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieRegionalRelease", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Certification")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("EffectiveReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("EffectiveReleaseType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFallbackGlobal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MovieId", "Region");

                    b.HasIndex("Region", "EffectiveReleaseDate");

                    b.ToTable("movie_regional_releases", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en-US");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedDeliverySecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasFilter("\"ImdbId\" IS NOT NULL");

                    b.HasIndex("Name");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasFilter("\"TvdbId\" IS NOT NULL");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.ProductMetricDaily", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MetricName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Date", "MetricName");

                    b.ToTable("product_metric_daily", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.PushDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentLocale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExpoPushToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpoPushToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("push_devices", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.PushNotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpoTicketId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PushDeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserReleaseNotificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedUntilUtc");

                    b.HasIndex("ExpoTicketId");

                    b.HasIndex("PushDeviceId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("UserReleaseNotificationId", "PushDeviceId")
                        .IsUnique();

                    b.ToTable("push_notification_deliveries", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MovieId");

                    b.HasIndex("TvShowId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasFilter("\"MovieId\" IS NOT NULL");

                    b.HasIndex("UserId", "TvShowId")
                        .IsUnique()
                        .HasFilter("\"TvShowId\" IS NOT NULL");

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ratings_catalog_reference", "(\"MovieId\" IS NOT NULL AND \"TvShowId\" IS NULL) OR (\"MovieId\" IS NULL AND \"TvShowId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ratings_score_range", "\"Score\" >= 1 AND \"Score\" <= 10");
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MovieId");

                    b.HasIndex("TvShowId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique()
                        .HasFilter("\"MovieId\" IS NOT NULL");

                    b.HasIndex("UserId", "TvShowId")
                        .IsUnique()
                        .HasFilter("\"TvShowId\" IS NOT NULL");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_reviews_catalog_reference", "(\"MovieId\" IS NOT NULL AND \"TvShowId\" IS NULL) OR (\"MovieId\" IS NULL AND \"TvShowId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NormalizedQuery");

                    b.HasIndex("UserId", "SearchedAt");

                    b.ToTable("search_histories", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.SearchProviderRefresh", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("LastRefreshedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedQuery", "ContentType", "Page")
                        .IsUnique();

                    b.ToTable("search_provider_refreshes", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasFilter("\"TvdbId\" IS NOT NULL");

                    b.HasIndex("TvShowId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TmdbTvChangesSyncCheckpoint", b =>
                {
                    b.Property<string>("CheckpointKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastCompletedEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CheckpointKey");

                    b.ToTable("tmdb_tv_changes_sync_checkpoints", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FirstAirDate")
                        .HasColumnType("date");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("KeywordsSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastAirDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Overview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VoteAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstAirDate");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasFilter("\"ImdbId\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" IS NOT NULL");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasFilter("\"TvdbId\" IS NOT NULL");

                    b.ToTable("tv_shows", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowCatalogSyncState", b =>
                {
                    b.Property<Guid>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("LastChangeSignalDate")
                        .HasColumnType("date");

                    b.Property<string>("LastRefreshReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastRefreshedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpcomingEpisodeSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextHotCheckAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TvShowId");

                    b.ToTable("tv_show_catalog_sync_states", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowGenre", b =>
                {
                    b.Property<Guid>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("TvShowId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("tv_show_genres", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowKeyword", b =>
                {
                    b.Property<Guid>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.HasKey("TvShowId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("tv_show_keywords", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowPerson", b =>
                {
                    b.Property<Guid>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreditType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Job")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Character")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TvShowId", "PersonId", "CreditType", "Job");

                    b.HasIndex("PersonId");

                    b.ToTable("tv_show_people", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAtLinkTime")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserReleaseNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregationWindowKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Body")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("Status");

                    b.HasIndex("TvShowId");

                    b.HasIndex("UserId")
                        .HasFilter("\"ReadAtUtc\" IS NULL");

                    b.HasIndex("UserId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("UserId", "TvShowId", "MovieId", "NotificationType", "AggregationWindowKey")
                        .IsUnique();

                    b.ToTable("user_release_notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_release_notifications_content_ref", "(\"TvShowId\" IS NOT NULL AND \"MovieId\" IS NULL) OR (\"TvShowId\" IS NULL AND \"MovieId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserReleaseNotificationEvent", b =>
                {
                    b.Property<Guid>("UserReleaseNotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogReleaseEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserReleaseNotificationId", "CatalogReleaseEventId");

                    b.HasIndex("CatalogReleaseEventId");

                    b.HasIndex("UserId", "CatalogReleaseEventId")
                        .IsUnique();

                    b.HasIndex("UserReleaseNotificationId", "CatalogReleaseEventId")
                        .IsUnique();

                    b.HasIndex("UserReleaseNotificationId", "UserId")
                        .HasDatabaseName("IX_user_release_notification_events_UserReleaseNotificationId~1");

                    b.ToTable("user_release_notification_events", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.WatchedEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("UserId");

                    b.HasIndex("WatchedAt");

                    b.HasIndex("UserId", "EpisodeId")
                        .IsUnique();

                    b.HasIndex("UserId", "WatchedAt");

                    b.ToTable("watched_episodes", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.WatchedMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.HasIndex("WatchedAt");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique();

                    b.HasIndex("UserId", "WatchedAt");

                    b.ToTable("watched_movies", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TvShowId");

                    b.HasIndex("WatchlistId");

                    b.HasIndex("WatchlistId", "MovieId")
                        .IsUnique()
                        .HasFilter("\"MovieId\" IS NOT NULL");

                    b.HasIndex("WatchlistId", "TvShowId")
                        .IsUnique()
                        .HasFilter("\"TvShowId\" IS NOT NULL");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.CatalogFollow", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("CatalogFollows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.CatalogReleaseEvent", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("CatalogReleaseEvents")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("CatalogReleaseEvents")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Movie");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Episode", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("Favorites")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("TvShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieGenre", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieKeyword", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Keyword", "Keyword")
                        .WithMany("MovieKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieKeywords")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MoviePerson", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("MoviePeople")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.Person", "Person")
                        .WithMany("MoviePeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.MovieRegionalRelease", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("RegionalReleases")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.PushDevice", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("PushDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.PushNotificationDelivery", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.PushDevice", "PushDevice")
                        .WithMany()
                        .HasForeignKey("PushDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.UserReleaseNotification", "UserReleaseNotification")
                        .WithMany()
                        .HasForeignKey("UserReleaseNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PushDevice");

                    b.Navigation("UserReleaseNotification");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Rating", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("Ratings")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("TvShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Review", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("Reviews")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("TvShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.SearchHistory", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Season", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowCatalogSyncState", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithOne("CatalogSyncState")
                        .HasForeignKey("MovieApp.Domain.Entities.TvShowCatalogSyncState", "TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowGenre", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Genre", "Genre")
                        .WithMany("TvShowGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("TvShowGenres")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowKeyword", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Keyword", "Keyword")
                        .WithMany("TvShowKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("TvShowKeywords")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShowPerson", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Person", "Person")
                        .WithMany("TvShowPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("TvShowPeople")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserReleaseNotification", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("ReleaseNotifications")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("ReleaseNotifications")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("ReleaseNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("TvShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserReleaseNotificationEvent", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.CatalogReleaseEvent", "ReleaseEvent")
                        .WithMany("NotificationEvents")
                        .HasForeignKey("CatalogReleaseEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.UserReleaseNotification", "Notification")
                        .WithMany("NotificationEvents")
                        .HasForeignKey("UserReleaseNotificationId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("ReleaseEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.WatchedEpisode", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Episode", "Episode")
                        .WithMany("WatchedEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("WatchedEpisodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.WatchedMovie", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("WatchedMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("WatchedMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("MovieApp.Domain.Entities.Movie", "Movie")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.TvShow", "TvShow")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Domain.Entities.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("TvShow");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.CatalogReleaseEvent", b =>
                {
                    b.Navigation("NotificationEvents");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Episode", b =>
                {
                    b.Navigation("WatchedEpisodes");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Genre", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("TvShowGenres");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Keyword", b =>
                {
                    b.Navigation("MovieKeywords");

                    b.Navigation("TvShowKeywords");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Movie", b =>
                {
                    b.Navigation("CatalogReleaseEvents");

                    b.Navigation("Favorites");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieKeywords");

                    b.Navigation("MoviePeople");

                    b.Navigation("Ratings");

                    b.Navigation("RegionalReleases");

                    b.Navigation("ReleaseNotifications");

                    b.Navigation("Reviews");

                    b.Navigation("WatchedMovies");

                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Person", b =>
                {
                    b.Navigation("MoviePeople");

                    b.Navigation("TvShowPeople");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.TvShow", b =>
                {
                    b.Navigation("CatalogReleaseEvents");

                    b.Navigation("CatalogSyncState");

                    b.Navigation("Favorites");

                    b.Navigation("Ratings");

                    b.Navigation("ReleaseNotifications");

                    b.Navigation("Reviews");

                    b.Navigation("Seasons");

                    b.Navigation("TvShowGenres");

                    b.Navigation("TvShowKeywords");

                    b.Navigation("TvShowPeople");

                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.User", b =>
                {
                    b.Navigation("CatalogFollows");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("ExternalLogins");

                    b.Navigation("Favorites");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("PushDevices");

                    b.Navigation("Ratings");

                    b.Navigation("ReleaseNotifications");

                    b.Navigation("Reviews");

                    b.Navigation("SearchHistories");

                    b.Navigation("WatchedEpisodes");

                    b.Navigation("WatchedMovies");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.UserReleaseNotification", b =>
                {
                    b.Navigation("NotificationEvents");
                });

            modelBuilder.Entity("MovieApp.Domain.Entities.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
