namespace MovieApp.Application.Services.CatalogShare;

internal static class PublicWebSiteCopy
{
    internal sealed record SiteCopy(
        string SiteTitle,
        string SiteDescription,
        string NavMovies,
        string NavTv,
        string OpenMovieCave,
        string TrendingMovies,
        string TrendingTv,
        string ValueHeadline,
        string ValueDiscover,
        string ValueRatings,
        string ValueLibrary,
        string ValueEpisodes,
        string MoviesPageTitle,
        string MoviesPageDescription,
        string TvPageTitle,
        string TvPageDescription,
        string RatingLabel);

    private static readonly Dictionary<string, SiteCopy> ByLanguage = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(
            "Movie Cave — Discover movies & TV",
            "Discover movies and TV shows, explore details, and track what you watch in Movie Cave.",
            "Movies",
            "TV Shows",
            "Open Movie Cave",
            "Trending Movies",
            "Trending TV Shows",
            "Everything you watch, in one place.",
            "Discover what to watch next",
            "Ratings, details, and trailers",
            "Your library and watchlists",
            "TV episode tracking",
            "Trending Movies — Movie Cave",
            "Explore trending movies on Movie Cave.",
            "Trending TV Shows — Movie Cave",
            "Explore trending TV shows on Movie Cave.",
            "Rating"),
        ["tr"] = new(
            "Movie Cave — Film ve dizi keşfi",
            "Film ve dizileri keşfet, detayları incele ve izlediklerini Movie Cave'de takip et.",
            "Filmler",
            "Diziler",
            "Movie Cave'i Aç",
            "Trend Filmler",
            "Trend Diziler",
            "İzlediğin her şey tek yerde.",
            "Sırada ne izleyeceğini keşfet",
            "Puanlar, detaylar ve fragmanlar",
            "Kütüphanen ve izleme listeleri",
            "Dizi bölüm takibi",
            "Trend Filmler — Movie Cave",
            "Movie Cave'de trend filmleri keşfet.",
            "Trend Diziler — Movie Cave",
            "Movie Cave'de trend dizileri keşfet.",
            "Puan"),
        ["de"] = new(
            "Movie Cave — Filme & Serien entdecken",
            "Entdecke Filme und Serien, sieh Details ein und verfolge deine Watchlist in Movie Cave.",
            "Filme",
            "Serien",
            "Movie Cave öffnen",
            "Trend-Filme",
            "Trend-Serien",
            "Alles, was du schaust, an einem Ort.",
            "Entdecke, was du als Nächstes schauen willst",
            "Bewertungen, Details und Trailer",
            "Deine Bibliothek und Watchlists",
            "Episoden-Fortschritt bei Serien",
            "Trend-Filme — Movie Cave",
            "Trend-Filme auf Movie Cave entdecken.",
            "Trend-Serien — Movie Cave",
            "Trend-Serien auf Movie Cave entdecken.",
            "Bewertung"),
        ["es"] = new(
            "Movie Cave — Descubre películas y series",
            "Descubre películas y series, explora detalles y lleva tu biblioteca en Movie Cave.",
            "Películas",
            "Series",
            "Abrir Movie Cave",
            "Películas en tendencia",
            "Series en tendencia",
            "Todo lo que ves, en un solo lugar.",
            "Descubre qué ver después",
            "Valoraciones, detalles y tráilers",
            "Tu biblioteca y listas",
            "Seguimiento de episodios",
            "Películas en tendencia — Movie Cave",
            "Explora películas en tendencia en Movie Cave.",
            "Series en tendencia — Movie Cave",
            "Explora series en tendencia en Movie Cave.",
            "Valoración"),
        ["fr"] = new(
            "Movie Cave — Films & séries",
            "Découvrez films et séries, explorez les détails et suivez vos visionnages dans Movie Cave.",
            "Films",
            "Séries",
            "Ouvrir Movie Cave",
            "Films tendance",
            "Séries tendance",
            "Tout ce que vous regardez, au même endroit.",
            "Découvrez quoi regarder ensuite",
            "Notes, détails et bandes-annonces",
            "Votre bibliothèque et listes",
            "Suivi des épisodes",
            "Films tendance — Movie Cave",
            "Explorez les films tendance sur Movie Cave.",
            "Séries tendance — Movie Cave",
            "Explorez les séries tendance sur Movie Cave.",
            "Note"),
        ["it"] = new(
            "Movie Cave — Film e serie TV",
            "Scopri film e serie, esplora i dettagli e tieni traccia di cosa guardi in Movie Cave.",
            "Film",
            "Serie TV",
            "Apri Movie Cave",
            "Film di tendenza",
            "Serie di tendenza",
            "Tutto ciò che guardi, in un unico posto.",
            "Scopri cosa guardare dopo",
            "Valutazioni, dettagli e trailer",
            "La tua libreria e le liste",
            "Tracciamento episodi TV",
            "Film di tendenza — Movie Cave",
            "Esplora i film di tendenza su Movie Cave.",
            "Serie di tendenza — Movie Cave",
            "Esplora le serie di tendenza su Movie Cave.",
            "Voto"),
        ["pt"] = new(
            "Movie Cave — Filmes e séries",
            "Descubra filmes e séries, veja detalhes e acompanhe o que assiste no Movie Cave.",
            "Filmes",
            "Séries",
            "Abrir Movie Cave",
            "Filmes em alta",
            "Séries em alta",
            "Tudo o que você assiste, em um só lugar.",
            "Descubra o que assistir a seguir",
            "Notas, detalhes e trailers",
            "Sua biblioteca e listas",
            "Acompanhamento de episódios",
            "Filmes em alta — Movie Cave",
            "Explore filmes em alta no Movie Cave.",
            "Séries em alta — Movie Cave",
            "Explore séries em alta no Movie Cave.",
            "Nota"),
    };

    internal static SiteCopy Resolve(string? acceptLanguageHeader)
    {
        var language = CatalogShareWebCopy.ResolveLanguageCode(acceptLanguageHeader);
        return ByLanguage.TryGetValue(language, out var copy) ? copy : ByLanguage["en"];
    }
}
